import os
import time
from sendtelegram.telegram import send_telegram
from env_setup import Credentials
from base.app import App_Object




def dict_compare(d1, d2):
    d1_keys = set(d1.keys())
    d2_keys = set(d2.keys())
    shared_keys = d1_keys.intersection(d2_keys)
    added = d1_keys - d2_keys
    removed = d2_keys - d1_keys
    modified = {o: (d1[o], d2[o]) for o in shared_keys if d1[o] != d2[o]}
    same = set(o for o in shared_keys if d1[o] == d2[o])
    return added, removed, modified, same


class Price_page(App_Object):
    EMAIL_FIELD = "#Email"
    PASSWORD_FIELD = "#Password"
    LOGIN_BUTTON = ".page-action-bar .btn"
    ass = '623914148'
    AROMA_BLOCK = ('.product-listing li')
    AROMA_NAME = ('.product-listing li h2')
    PRICE = (f' li:nth-child({1}) .addtocart option')
    spisok = []
    names_list = {}
    data = {'Absinthe Flavor **': ['gallon - Price: $119.70 (USD)', 'case - Price: $460.00 (USD)'],
            'Absinthe II Flavor': ['gallon - Price: $133.80 (USD)', 'case - Price: $528.00 (USD)'],
            'Acai Flavor': ['gallon - Price: $110.00 (USD)', 'case - Price: $420.00 (USD)',
                            'double case - Price: $824.00 (USD)'],
            'Acetyl Pyrazine 5 PG': ['gallon - Price: $220.00 (USD)', 'case (4 gallons) - Price: $800.00 (USD)',
                                     'double case - Price: $1,560.00 (USD)'],
            'Almond Amaretto Flavor': ['gallon - Price: $55.00 (USD)', 'case - Price: $320.00 (USD)'],
            'Almond Flavor': ['gallon - Price: $55.00 (USD)'],
            'Apple (Tart Granny Smith) Flavor **': ['gallon - Price: $114.00 (USD)', 'case - Price: $416.00 (USD)'],
            'Apple (Tart Green Apple) Flavor': ['gallon - Price: $135.00 (USD)', 'case - Price: $520.00 (USD)',
                                                'double case - Price: $1,024.00 (USD)'],
            'Apple Candy Flavor**': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $416.00 (USD)',
                                     'double case - Price: $808.24 (USD)'],
            'Apple Flavor': ['gallon - Price: $102.60 (USD)', 'case (4 gallons) - Price: $360.00 (USD)',
                             'double case - Price: $679.78 (USD)'],
            'Apple Pie Flavor': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $420.00 (USD)',
                                 'double case - Price: $768.24 (USD)'],
            'Apricot Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $360.00 (USD)'],
            'Banana Cream Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $336.00 (USD)',
                                    'double case - Price: $660.00 (USD)'],
            'Banana Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $320.00 (USD)',
                              'double case - Price: $624.00 (USD)'],
            'Banana Nut Bread Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $334.00 (USD)',
                                        'double case - Price: $652.00 (USD)'],
            'Bananas Foster Flavor': ['gallon - Price: $127.00 (USD)', 'case - Price: $500.00 (USD)',
                                      'double case - Price: $992.00 (USD)'],
            'Bavarian Cream Flavor': ['gallon - Price: $99.75 (USD)', 'case (4 gallons) - Price: $392.00 (USD)',
                                      'double case (8) - Price: $774.00 (USD)'],
            'Berry Cereal Flavor': ['gallon - Price: $126.75 (USD)', 'case (4 gallons) - Price: $500.00 (USD)',
                                    'double case - Price: $984.00 (USD)'],
            'Berry Mix Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $448.00 (USD)',
                                 'double case - Price: $880.00 (USD)'],
            'Berry Tobacco Type Flavor CC': ['gallon - Price: $240.00 (USD)'],
            'Birch Beer and Tobacco Type Flavor CC': ['gallon - Price: $260.00 (USD)'],
            'Bitter Nut Extra Flavor': ['gallon - Price: $240.00 (USD)', 'case - Price: $928.00 (USD)'],
            'Bittersweet Chocolate Flavor': ['gallon - Price: $148.20 (USD)'],
            'Black Cherry Flavor': ['gallon - Price: $91.20 (USD)', 'case (4 gallons) - Price: $320.00 (USD)',
                                    'double case - Price: $624.00 (USD)'],
            'Black Currant Flavor': ['gallon - Price: $96.00 (USD)', 'case (4 gallons) - Price: $376.00 (USD)',
                                     'double case - Price: $736.00 (USD)'],
            'Black Honey Flavor': ['gallon - Price: $116.00 (USD)', 'case - Price: $424.00 (USD)',
                                   'double case - Price: $800.00 (USD)'],
            'Blackberry Flavor': ['gallon - Price: $91.20 (USD)', 'case (4 gallons) - Price: $356.80 (USD)',
                                  'double case - Price: $697.60 (USD)'],
            'Blue Raspberry Flavor **': ['gallon - Price: $226.00 (USD)', 'case - Price: $896.00 (USD)'],
            'Blueberry (Wild) Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                                        'double case - Price: $648.00 (USD)'],
            'Blueberry Candy Flavor (PG)': ['gallon - Price: $148.20 (USD)', 'case (4 gallons) - Price: $552.80 (USD)',
                                            'double case - Price: $1,099.00 (USD)'],
            'Blueberry Candy Flavor (Triacetin)': ['gallon - Price: $95.00 (USD)'],
            'Blueberry Flavor (Extra)': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                                         'double case - Price: $648.00 (USD)'],
            'Bourbon Flavor': ['gallon - Price: $127.50 (USD)', 'case - Price: $504.00 (USD)'],
            'Boysenberry Deluxe Flavor': ['gallon - Price: $148.00 (USD)'],
            'Boysenberry Flavor **': ['gallon - Price: $150.00 (USD)'],
            'Brandy Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $336.00 (USD)'],
            'Brown Sugar Flavor': ['gallon - Price: $116.85 (USD)', 'case (4 gallons) - Price: $427.40 (USD)',
                                   'double case - Price: $812.00 (USD)'],
            'Bubblegum (Fruity) Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $332.00 (USD)',
                                             'double case - Price: $648.00 (USD)'],
            'Bubblegum Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $334.00 (USD)',
                                 'double case - Price: $652.00 (USD)'],
            'Butter Flavor': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $438.80 (USD)',
                              'double case - Price: $864.00 (USD)'],
            'Butterscotch Flavor': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $444.00 (USD)',
                                    'double case - Price: $872.00 (USD)'],
            'Butterscotch II Flavor': ['gallon - Price: $75.00 (USD)'],
            'Cannabis Type Flavor**': ['case - Price: $416.00 (USD)'],
            'Cantaloupe Flavor': ['gallon - Price: $120.00 (USD)', 'case (4 gallons) - Price: $472.00 (USD)',
                                  'double case - Price: $928.00 (USD)'],
            'Cappuccino Flavor': ['gallon - Price: $91.20 (USD)', 'case - Price: $352.00 (USD)'],
            'Caramel (Original) Flavor': ['gallon - Price: $91.20 (USD)', 'case - Price: $356.80 (USD)',
                                          'double case - Price: $697.60 (USD)'],
            'Caramel Candy Flavor': ['gallon - Price: $95.00 (USD)', 'case (4 gallons) - Price: $368.00 (USD)',
                                     'double case - Price: $720.00 (USD)'],
            'Caramel Cappuccino Flavor': ['gallon - Price: $175.00 (USD)', 'case - Price: $680.00 (USD)'],
            'Caramel Flavor': ['gallon - Price: $91.20 (USD)', 'case - Price: $356.00 (USD)',
                               'double case - Price: $696.00 (USD)'],
            'Chai Tea Flavor **': ['gallon - Price: $115.00 (USD)', 'case - Price: $420.00 (USD)',
                                   'double case - Price: $824.00 (USD)'],
            'Chai Tea II Flavor': ['gallon - Price: $85.00 (USD)'],
            'Champagne Type Flavor (PG)': ['gallon - Price: $85.00 (USD)', 'case - Price: $328.00 (USD)',
                                           'double case - Price: $640.00 (USD)'],
            'Cheesecake Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)',
                                  'double case - Price: $550.00 (USD)'],
            'Cheesecake Flavor (Graham Crust)': ['gallon - Price: $105.00 (USD)', 'case - Price: $412.00 (USD)',
                                                 'double case - Price: $808.00 (USD)'],
            'Cherry Blossom (PG)': ['gallon - Price: $148.20 (USD)', 'case - Price: $480.00 (USD)'],
            'Cherry Extract Flavor**': ['gallon - Price: $85.00 (USD)', 'case - Price: $320.00 (USD)',
                                        'double case - Price: $600.00 (USD)'],
            'Chili Mango Flavor': ['gallon - Price: $137.58 (USD)', 'case (4 gallons) - Price: $540.00 (USD)'],
            'Chocolate Coconut Almond Candy Bar Flavor': ['gallon - Price: $89.80 (USD)'],
            'Chocolate Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)',
                                 'double case - Price: $547.08 (USD)'],
            'Cigarillo Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $332.00 (USD)',
                                 'double case - Price: $656.00 (USD)'],
            'Cinnamon Danish Flavor': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)',
                                       'double case - Price: $748.00 (USD)'],
            'Cinnamon Flavor **': ['gallon - 2 week lead time - Price: $80.00 (USD)', 'case - Price: $357.60 (USD)'],
            'Cinnamon Red Hot (PG)': ['gallon - Price: $100.00 (USD)', 'case - Price: $360.00 (USD)'],
            'Cinnamon Red Hot Flavor**': ['gallon - Price: $100.00 (USD)', 'case (4 gallons) - Price: $388.00 (USD)',
                                          'double case - Price: $752.00 (USD)'],
            'Cinnamon Spice Flavor': ['gallon - Price: $110.00 (USD)', 'case - Price: $400.00 (USD)'],
            'Cinnamon Sugar Cookie': ['gallon - Price: $92.00 (USD)', 'case - Price: $360.00 (USD)',
                                      'double case - Price: $696.00 (USD)'],
            'Citrus Punch Flavor **': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                                       'double case - Price: $648.00 (USD)'],
            'Citrus Punch II Flavor': ['gallon - Price: $96.90 (USD)', 'case - Price: $372.00 (USD)',
                                       'double case - Price: $728.00 (USD)'],
            'Clove Flavor': ['gallon - Price: $125.00 (USD)', 'case - Price: $475.00 (USD)'],
            'Cocoa Rounds Flavor': ['gallon - Price: $135.00 (USD)', 'case - Price: $528.00 (USD)'],
            'Cocoa Tobacco Type Flavor CC': ['gallon - Price: $280.00 (USD)'],
            'Coconut Candy Flavor': ['gallon - Price: $117.00 (USD)', 'case - Price: $462.00 (USD)',
                                     'double case - Price: $912.00 (USD)'],
            'Coconut Extra Flavor': ['gallon - Price: $148.20 (USD)', 'case - Price: $552.00 (USD)',
                                     'double case - Price: $1,088.00 (USD)'],
            'Coconut Flavor': ['gallon - Price: $102.00 (USD)', 'case (4 gallons) - Price: $400.00 (USD)',
                               'double case - Price: $776.00 (USD)'],
            'Coffee (Kona) Flavor': ['gallon - Price: $115.00 (USD)'],
            'Coffee Flavor': ['gallon - Price: $96.90 (USD)', 'case - Price: $347.60 (USD)'],
            'Cola Cherry Flavor': ['gallon - Price: $150.00 (USD)', 'case - Price: $592.00 (USD)'],
            'Cola Fizz Flavor**': ['gallon - Price: $117.00 (USD)', 'case - Price: $428.00 (USD)',
                                   'double case - Price: $791.52 (USD)'],
            'Cola Flavor**': ['gallon - Price: $117.00 (USD)', 'case - Price: $460.00 (USD)',
                              'double case - Price: $912.00 (USD)'],
            'Cardamom Flavor': ['gallon - Price: $105.00 (USD)'],
            'Cola Soda Flavor': ['gallon - Price: $170.00 (USD)', 'case - Price: $672.00 (USD)'],
            'Cola Syrup Flavor**': ['gallon - Price: $102.00 (USD)', 'case - Price: $368.00 (USD)',
                                    'double case - Price: $720.00 (USD)'],
            'Cotton Candy (Circus)': ['gallon - Price: $119.00 (USD)', 'case - Price: $468.00 (USD)',
                                      'double case - Price: $920.00 (USD)'],
            'Cotton Candy Flavor': ['gallon - Price: $84.00 (USD)', 'case (4 gallons) - Price: $328.00 (USD)',
                                    'double case - Price: $640.00 (USD)'],
            'Cranberry Flavor**': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)',
                                   'double case - Price: $736.00 (USD)'],
            'Cranberry Sauce Flavor': ['gallon - Price: $133.00 (USD)', 'case - Price: $524.00 (USD)'],
            'Cream Soda Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $322.00 (USD)',
                                  'double case - Price: $608.00 (USD)'],
            'Creme de Menthe Flavor **': ['gallon - Price: $91.20 (USD)', 'case - Price: $356.00 (USD)',
                                          'double case - Price: $696.00 (USD)'],
            'Creme de Menthe II Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $448.00 (USD)',
                                          'double case - Price: $880.00 (USD)'],
            'Crunchy Cereal Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $416.00 (USD)',
                                      'double case - Price: $808.24 (USD)'],
            'Cubano Type Flavor': ['gallon - Price: $105.00 (USD)', 'case - Price: $360.00 (USD)',
                                   'double case - Price: $712.00 (USD)'],
            'Cucumber Deluxe Flavor': ['gallon - Price: $148.20 (USD)', 'case - Price: $552.00 (USD)'],
            'Cucumber Flavor **': ['gallon - Price: $114.00 (USD)', 'case - Price: $440.00 (USD)',
                                   'double case - Price: $763.00 (USD)'],
            'Concord Grape Juice Flavor **': ['gallon - Price: $119.70 (USD)', 'case - Price: $468.00 (USD)',
                                              'double case - Price: $920.00 (USD)'],
            'Blood Orange Flavor': ['gallon - Price: $85.00 (USD)', 'case (4 gallons) - Price: $400.00 (USD)'],
            'Dairy/Milk Flavor': ['gallon - Price: $71.25 (USD)', 'case (4 gallons) - Price: $280.00 (USD)',
                                  'double case - Price: $548.00 (USD)'],
            'Dark Rum Flavor': ['gallon - Price: $135.00 (USD)', 'case - Price: $528.00 (USD)'],
            'DK Tobacco Base Flavor **': ['gallon - Price: $165.00 (USD)', 'case - Price: $644.00 (USD)',
                                          'double case - Price: $1,276.00 (USD)'],
            'DK Tobacco II Flavor': ['gallon - Price: $230.80 (USD)', 'case - Price: $916.00 (USD)',
                                     'double case - Price: $1,816.00 (USD)'],
            'Double Chocolate (Clear) Flavor': ['gallon - Price: $140.00 (USD)',
                                                'case (4 gallons) - Price: $520.00 (USD)',
                                                'double case - Price: $1,010.00 (USD)'],
            'Double Chocolate (Dark) Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $416.00 (USD)',
                                               'double case - Price: $816.00 (USD)'],
            'Dr. Pop Flavor': ['gallon - Price: $119.00 (USD)', 'case - Price: $440.50 (USD)'],
            'Dragonfruit Flavor': ['gallon - Price: $91.20 (USD)', 'case (4 gallons) - Price: $356.80 (USD)',
                                   'double case - Price: $697.60 (USD)'],
            'Dulce de Leche Caramel Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $444.00 (USD)',
                                              'double case - Price: $872.00 (USD)'],
            'Dulce de Leche Flavor **': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $444.00 (USD)',
                                         'double case - Price: $864.00 (USD)'],
            'DX Banana Cream': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $334.00 (USD)',
                                'double case - Price: $652.00 (USD)'],
            'DX Bananas Foster Flavor': ['gallon - Price: $120.00 (USD)', 'case - Price: $450.00 (USD)'],
            'DX Bavarian Cream': ['gallon - Price: $99.75 (USD)', 'case (4 gallons) - Price: $392.00 (USD)',
                                  'double case - Price: $768.00 (USD)'],
            'DX Brown Sugar Flavor': ['gallon - Price: $147.25 (USD)', 'case - Price: $584.00 (USD)'],
            'DX Butterscotch Flavor': ['gallon - Price: $104.00 (USD)'],
            'DX Caramel Original': ['gallon - Price: $91.20 (USD)', 'case (4 gallons) - Price: $324.80 (USD)',
                                    'double case - Price: $609.60 (USD)'],
            'DX Cinnamon Danish': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)'],
            'DX Coconut Candy Flavor': ['gallon - Price: $110.00 (USD)', 'case - Price: $400.00 (USD)',
                                        'double case - Price: $737.20 (USD)'],
            'DX Coconut Flavor': ['gallon - Price: $110.00 (USD)', 'case - Price: $420.00 (USD)',
                                  'double case - Price: $800.00 (USD)'],
            'DX Frosted Donut Flavor': ['gallon - Price: $100.00 (USD)', 'case - Price: $375.00 (USD)',
                                        'double case - Price: $742.00 (USD)'],
            'DX Graham Cracker Flavor': ['gallon - Price: $119.70 (USD)', 'case - Price: $454.80 (USD)'],
            'DX Hazelnut Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $376.00 (USD)',
                                   'double case - Price: $736.00 (USD)'],
            'DX Jamaican Rum Flavor': ['gallon - Price: $129.00 (USD)', 'case - Price: $480.00 (USD)'],
            'DX Marshmallow Flavor': ['gallon - Price: $110.00 (USD)', 'case - Price: $400.00 (USD)'],
            'DX Milk Chocolate Flavor': ['gallon - Price: $105.00 (USD)', 'case - Price: $416.00 (USD)'],
            'DX Milk Flavor': ['gallon - Price: $102.60 (USD)', 'case - Price: $396.00 (USD)',
                               'double case - Price: $776.00 (USD)'],
            'DX Peach (Juicy) Flavor': ['gallon - Price: $84.00 (USD)', 'case (4 gallons) - Price: $364.00 (USD)',
                                        'double case - Price: $712.00 (USD)'],
            'DX Peanut Butter Flavor': ['gallon - Price: $102.60 (USD)', 'case (4 gallons) - Price: $400.00 (USD)',
                                        'double case - Price: $784.00 (USD)'],
            'DX Pistachio Flavor': ['case - Price: $387.60 (USD)'],
            'DX Sweet Cream Flavor': ['gallon - Price: $102.60 (USD)', 'case - Price: $400.00 (USD)',
                                      'double case - Price: $784.00 (USD)'],
            'DX Vanilla Cupcake': ['gallon - Price: $105.00 (USD)', 'case (4 gallons) - Price: $380.00 (USD)',
                                   'double case - Price: $712.00 (USD)'],
            'Earl Grey Tea Flavor **': ['gallon - Price: $148.20 (USD)', 'case - Price: $572.80 (USD)'],
            'Egg Nog Flavor': ['gallon - Price: $114.00 (USD)'],
            'Elderberry Flavor': ['gallon - Price: $65.00 (USD)', 'case - Price: $372.00 (USD)'],
            'Energy Drink Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                                    'double case - Price: $640.00 (USD)'],
            'English Toffee Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $452.00 (USD)',
                                      'double case - Price: $896.00 (USD)'],
            'Espresso Flavor': ['gallon - Price: $96.90 (USD)', 'case - Price: $376.00 (USD)'],
            'French Vanilla Creme': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $420.00 (USD)',
                                     'double case - Price: $800.00 (USD)'],
            'French Vanilla Deluxe Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $444.00 (USD)',
                                             'double case - Price: $872.00 (USD)'],
            'French Vanilla Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $376.00 (USD)',
                                      'double case - Price: $736.00 (USD)'],
            'French Vanilla II Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $300.00 (USD)',
                                         'double case - Price: $560.00 (USD)'],
            'Fresh Mint Flavor CC': ['gallon - Price: $120.00 (USD)'],
            'Frosted Donut Flavor': ['gallon - Price: $105.00 (USD)', 'case (4 gallons) - Price: $380.00 (USD)',
                                     'double case - Price: $720.00 (USD)'],
            'Fruit Circles Flavor': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $448.00 (USD)',
                                     'double case - Price: $880.00 (USD)'],
            'Fruit Circles With Milk Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $300.00 (USD)',
                                               'double case - Price: $584.00 (USD)'],
            'Fruit Smoothie Flavor**': ['gallon - Price: $75.00 (USD)', 'case (4 gallons) - Price: $284.00 (USD)'],
            'Fruity Stick Gum Flavor': ['gallon - Price: $105.50 (USD)', 'case - Price: $412.00 (USD)',
                                        'double case - Price: $808.00 (USD)'],
            'Ginger Ale Flavor (NF)': ['gallon - Price: $92.80 (USD)'],
            'Ginger Ale Flavor **': ['gallon - Price: $89.50 (USD)'],
            'Gingerbread Cookie': ['gallon - Price: $185.00 (USD)', 'case - Price: $592.00 (USD)'],
            'Graham Cracker Clear': ['gallon - Price: $107.90 (USD)', 'case (4 gallons) - Price: $424.00 (USD)',
                                     'double case - Price: $836.00 (USD)'],
            'Graham Cracker Flavor': ['gallon - Price: $119.70 (USD)', 'case - Price: $454.80 (USD)',
                                      'double case - Price: $894.00 (USD)'],
            'Grape Candy Flavor**': ['gallon - Price: $92.00 (USD)', 'case (4 gallons) - Price: $356.00 (USD)',
                                     'double case - Price: $696.00 (USD)'],
            'Grape Juice Flavor**': ['gallon - Price: $85.50 (USD)', 'case - Price: $336.00 (USD)',
                                     'double case - Price: $652.00 (USD)'],
            'Grape Soda Flavor': ['gallon - Price: $130.00 (USD)', 'case (4 gallons) - Price: $475.00 (USD)',
                                  'double case - Price: $896.00 (USD)'],
            'Greek Yogurt Flavor': ['gallon - Price: $132.00 (USD)', 'case (4 gallons) - Price: $524.00 (USD)',
                                    'double case - Price: $1,040.00 (USD)'],
            'Green Apple Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $376.00 (USD)',
                                   'double case - Price: $736.00 (USD)'],
            'Green Tea Flavor': ['gallon - Price: $202.50 (USD)', 'case - Price: $760.00 (USD)',
                                 'double case - Price: $1,480.00 (USD)'],
            'Guava Flavor': ['gallon - Price: $129.00 (USD)', 'case - Price: $496.00 (USD)'],
            'Gummy Candy (PG) Flavor': ['gallon - Price: $96.30 (USD)', 'case (4 gallons) - Price: $345.20 (USD)',
                                        'double case - Price: $650.40 (USD)'],
            'Gummy Candy Flavor': ['gallon - Price: $96.90 (USD)', 'case - Price: $347.60 (USD)'],
            'Hawaiian Drink Flavor**': ['gallon - Price: $162.00 (USD)', 'case - Price: $640.00 (USD)',
                                        'double case - Price: $1,264.00 (USD)'],
            'Hazelnut Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $347.60 (USD)',
                                'double case - Price: $672.00 (USD)'],
            'Hazelnut Praline Flavor': ['gallon - Price: $134.60 (USD)', 'case - Price: $532.00 (USD)'],
            'Hibiscus Flavor': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)',
                                'double case - Price: $744.00 (USD)'],
            'Hickory Smoke Flavor': ['gallon - Price: $79.10 (USD)'],
            'Honey Circles Cereal Flavor': ['gallon - Price: $91.50 (USD)', 'case - Price: $356.00 (USD)',
                                            'double case - Price: $945.00 (USD)'],
            'Honey Flavor': ['gallon - Price: $85.50 (USD)'],
            'Honey Orange Tobacco Type Flavor CC': ['gallon - Price: $280.00 (USD)'],
            'Honey Tobacco Type Flavor CC': ['gallon - Price: $210.00 (USD)', 'case - Price: $828.00 (USD)'],
            'Honeydew Flavor **': ['gallon - Price: $290.00 (USD)', 'case - Price: $1,120.00 (USD)',
                                   'double case - Price: $2,160.00 (USD)'],
            'Honeydew II Flavor': ['gallon - Price: $195.80 (USD)', 'case (4 gallons) - Price: $776.00 (USD)',
                                   'double case - Price: $1,544.00 (USD)'],
            'Honeysuckle Flavor (PG)': ['gallon - Price: $129.00 (USD)', 'case - Price: $476.00 (USD)',
                                        'double case - Price: $912.00 (USD)'],
            'Horchata Smooth Flavor': ['gallon - Price: $139.30 (USD)', 'case - Price: $552.00 (USD)'],
            'Horehound Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $320.00 (USD)'],
            'Hpno II Flavor': ['gallon - Price: $69.61 (USD)', 'case - Price: $272.00 (USD)',
                               'double case - Price: $536.00 (USD)'],
            'Hpno Type Flavor **': ['gallon - Price: $91.20 (USD)', 'case - Price: $324.80 (USD)'],
            'Irish Cream Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)',
                                      'double case - Price: $547.08 (USD)'],
            'Irish Cream II Flavor': ['gallon - Price: $87.80 (USD)'],
            'Jackfruit Flavor': ['gallon - Price: $120.00 (USD)', 'case - Price: $474.00 (USD)',
                                 'double case - Price: $936.00 (USD)'],
            'Jamaican Rum Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $316.50 (USD)'],
            'Kalua and Cream Flavor': ['gallon - Price: $83.60 (USD)', 'case - Price: $592.00 (USD)'],
            'Kentucky Bourbon Flavor **': ['gallon - Price: $102.60 (USD)', 'case - Price: $370.40 (USD)'],
            'Kettle Corn Flavor': ['gallon - Price: $91.00 (USD)', 'case - Price: $324.00 (USD)',
                                   'double case - Price: $632.00 (USD)'],
            'Key Lime Flavor **': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                                   'double case - Price: $648.00 (USD)'],
            'Key Lime Pie Flavor': ['gallon - Price: $133.10 (USD)', 'case - Price: $528.00 (USD)',
                                    'double case - Price: $1,040.00 (USD)'],
            'Kiwi (Double) Flavor': ['gallon - Price: $98.00 (USD)', 'case (4 gallons) - Price: $384.00 (USD)',
                                     'double case - Price: $752.00 (USD)'],
            'Koolada 10 PG': ['gallon - Price: $145.00 (USD)', 'case (4 gallons) - Price: $570.00 (USD)',
                              'double case - Price: $1,120.00 (USD)'],
            'Lavender Flavor': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)'],
            'Lemon (water soluble) Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $336.00 (USD)',
                                                'double case - Price: $656.00 (USD)'],
            'Lemon II Flavor': ['gallon - Price: $115.70 (USD)', 'case - Price: $456.00 (USD)',
                                'double case - Price: $904.00 (USD)'],
            'Lemon Lime Flavor**': ['gallon - Price: $96.90 (USD)', 'case - Price: $347.60 (USD)',
                                    'double case - Price: $687.20 (USD)'],
            'Lemon Lime II Flavor': ['gallon - Price: $116.60 (USD)', 'case - Price: $460.00 (USD)',
                                     'double case - Price: $912.00 (USD)'],
            'Lemonade Cookie Flavor': ['gallon - Price: $129.00 (USD)', 'case - Price: $476.00 (USD)',
                                       'double case - Price: $936.00 (USD)'],
            'Licorice Tobacco Flavor CC': ['gallon - Price: $119.70 (USD)'],
            'Lucky Leprechaun Cereal Flavor': ['gallon - Price: $95.00 (USD)',
                                               'case (4 gallons) - Price: $340.00 (USD)',
                                               'double case - Price: $656.00 (USD)'],
            'Lychee Flavor': ['gallon - Price: $96.00 (USD)', 'case - Price: $372.00 (USD)'],
            'Malted Milk (Conc) Flavor': ['gallon - Price: $102.00 (USD)', 'case (4 gallons) - Price: $380.00 (USD)',
                                          'double case - Price: $720.00 (USD)'],
            'Mango Flavor': ['gallon - Price: $95.00 (USD)', 'case (4 gallons) - Price: $368.00 (USD)',
                             'double case - Price: $712.00 (USD)'],
            'Maple Deluxe Flavor': ['gallon - Price: $125.90 (USD)', 'case - Price: $500.00 (USD)',
                                    'double case - Price: $984.00 (USD)'],
            'Maple Flavor**': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)'],
            'Maple Syrup Flavor': ['gallon - Price: $91.20 (USD)', 'case - Price: $324.80 (USD)',
                                   'double case - Price: $600.00 (USD)'],
            'Maraschino Cherry (PG)': ['gallon - Price: $96.90 (USD)', 'case - Price: $347.60 (USD)'],
            'Marshmallow Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $336.00 (USD)',
                                   'double case - Price: $656.00 (USD)'],
            'Mary Jane Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)',
                                 'double case - Price: $584.00 (USD)'],
            'Menthol Liquid (PG)': ['gallon - Price: $290.00 (USD)', 'case (4 gallons) - Price: $1,144.00 (USD)',
                                    'double case - Price: $2,256.00 (USD)'],
            'Meringue Flavor': ['gallon - Price: $123.00 (USD)', 'case (4 gallons) - Price: $488.00 (USD)',
                                'double case - Price: $968.00 (USD)'],
            'Mexican Coffee Flavor': ['gallon - Price: $105.00 (USD)'],
            'Midwest Tobacco Type Flavor CC': ['gallon - Price: $240.00 (USD)'],
            'Milk Chocolate Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                                      'double case - Price: $648.00 (USD)'],
            'Mint Candy Flavor': ['gallon - Price: $120.00 (USD)', 'case - Price: $440.00 (USD)',
                                  'double case - Price: $800.00 (USD)'],
            'Mint Flavor CC': ['gallon - Price: $99.75 (USD)'],
            'Mocha Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $328.00 (USD)'],
            'Mojito Flavor **': ['gallon - Price: $129.00 (USD)', 'case (4 gallons) - Price: $460.00 (USD)',
                                 'double case - Price: $896.00 (USD)'],
            'Mojito Havana Flavor': ['gallon - Price: $143.80 (USD)', 'case - Price: $568.00 (USD)',
                                     'double case - Price: $1,128.00 (USD)'],
            'Molasses Flavor': ['gallon - Price: $86.00 (USD)', 'case - Price: $304.00 (USD)'],
            'Musk Candy Flavor': ['gallon - Price: $75.00 (USD)'],
            'Nectarine Flavor': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $438.80 (USD)',
                                 'double case - Price: $837.60 (USD)'],
            'Oatmeal Cookie Flavor': ['gallon - Price: $120.00 (USD)', 'case - Price: $475.00 (USD)',
                                      'double case - Price: $904.00 (USD)'],
            'Orange Cream Bar Flavor': ['gallon - Price: $90.50 (USD)', 'case - Price: $428.00 (USD)',
                                        'double case - Price: $840.00 (USD)'],
            'Orange Cream Flavor **': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $300.00 (USD)',
                                       'double case - Price: $587.08 (USD)'],
            'Orange Mandarin Flavor': ['gallon - Price: $110.00 (USD)', 'case (4 gallons) - Price: $400.00 (USD)',
                                       'double case - Price: $776.00 (USD)'],
            'Organic Compliant Strawberry Flavor **': ['gallon - Price: $162.90 (USD)', 'case - Price: $640.00 (USD)'],
            'Pancake Flavor': ['gallon - Price: $130.00 (USD)', 'case - Price: $500.00 (USD)'],
            'Papaya Flavor': ['gallon - Price: $97.00 (USD)', 'case (4 gallons) - Price: $380.00 (USD)',
                              'double case - Price: $744.00 (USD)'],
            'Papaya II Flavor': ['gallon - Price: $97.00 (USD)', 'case (4 gallons) - Price: $348.00 (USD)'],
            'Passion Fruit Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $328.00 (USD)'],
            'Passion Orange Guava Flavor': ['gallon - Price: $119.00 (USD)', 'case (4 gallons) - Price: $464.00 (USD)',
                                            'double case - Price: $912.00 (USD)'],
            'Peach (Juicy) Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $332.00 (USD)',
                                     'double case - Price: $648.00 (USD)'],
            'Peach Flavor': ['gallon - Price: $88.00 (USD)', 'case (4 gallons) - Price: $344.00 (USD)',
                             'double case - Price: $672.00 (USD)'],
            'Peach Yogurt Flavor': ['gallon - Price: $86.15 (USD)', 'case (4 gallons) - Price: $464.00 (USD)'],
            'Peanut Butter Flavor': ['gallon - Price: $102.60 (USD)', 'case (4 gallons) - Price: $400.00 (USD)',
                                     'double case - Price: $784.00 (USD)'],
            'Pear Candy Flavor': ['gallon - Price: $96.90 (USD)', 'case - Price: $368.00 (USD)',
                                  'double case - Price: $720.00 (USD)'],
            'Pear Flavor': ['gallon - Price: $160.00 (USD)', 'case (4 gallons) - Price: $628.00 (USD)',
                            'double case (8) - Price: $1,240.00 (USD)'],
            'Pecan Flavor': ['gallon - Price: $65.00 (USD)', 'case - Price: $400.00 (USD)'],
            'Peppermint Flavor **': ['gallon - Price: $125.40 (USD)', 'case (4 gallons) - Price: $481.60 (USD)',
                                     'double case - Price: $936.00 (USD)'],
            'Peppermint II Flavor': ['gallon - Price: $135.00 (USD)', 'case - Price: $520.00 (USD)',
                                     'double case - Price: $1,000.00 (USD)'],
            'Philippine Mango Flavor': ['gallon - Price: $90.00 (USD)', 'case - Price: $340.00 (USD)',
                                        'double case - Price: $656.00 (USD)'],
            'Pie Crust Flavor': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $438.80 (USD)',
                                 'double case - Price: $835.00 (USD)'],
            'Pina Colada Flavor': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $436.00 (USD)',
                                   'double case - Price: $840.00 (USD)'],
            'Pineapple Flavor **': ['gallon - Price: $102.60 (USD)', 'case (4 gallons) - Price: $400.00 (USD)',
                                    'double case - Price: $776.00 (USD)'],
            'Pineapple Juicy Flavor': ['gallon - Price: $135.00 (USD)', 'case (4 gallons) - Price: $532.00 (USD)',
                                       'double case - Price: $1,056.00 (USD)'],
            'Pistachio Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $347.60 (USD)',
                                 'double case - Price: $656.00 (USD)'],
            'Plum Flavor (PG)': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)'],
            'Pomegranate Deluxe': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $438.80 (USD)',
                                   'double case - Price: $837.60 (USD)'],
            'Pomegranate Flavor': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $440.00 (USD)',
                                   'double case - Price: $852.47 (USD)'],
            'Popcorn Air Popped Flavor': ['gallon - Price: $150.00 (USD)', 'case - Price: $592.00 (USD)'],
            'Popcorn Flavor': ['gallon - Price: $125.40 (USD)', 'case - Price: $481.60 (USD)',
                               'double case - Price: $918.78 (USD)'],
            'Popcorn Movie Theater Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $416.00 (USD)'],
            'Pumpkin Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)'],
            'Quince Flavor **': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)'],
            'Rainbow Drops Flavor (NF)': ['gallon - Price: $135.00 (USD)', 'case - Price: $528.00 (USD)'],
            'Rainbow Drops Flavor **': ['gallon - Price: $129.00 (USD)', 'case (4 gallons) - Price: $512.00 (USD)',
                                        'double case - Price: $1,016.00 (USD)'],
            'Rainbow Sherbet Flavor': ['gallon - Price: $114.00 (USD)', 'case (4 gallons) - Price: $440.00 (USD)',
                                       'double case - Price: $856.00 (USD)'],
            'Raisin Flavor': ['gallon - Price: $119.70 (USD)', 'case - Price: $460.00 (USD)'],
            'Raspberry (Sweet) Flavor': ['gallon - Price: $97.00 (USD)', 'case (4 gallons) - Price: $348.00 (USD)',
                                         'double case - Price: $636.32 (USD)'],
            'Raspberry Flavor**': ['gallon - Price: $129.00 (USD)', 'case - Price: $500.00 (USD)',
                                   'double case - Price: $960.00 (USD)'],
            'Red Licorice Flavor': ['gallon - Price: $102.60 (USD)', 'case - Price: $360.00 (USD)',
                                    'double case - Price: $656.00 (USD)'],
            'Red Oak Flavor': ['gallon - Price: $119.70 (USD)', 'case - Price: $438.80 (USD)',
                               'double case - Price: $840.00 (USD)'],
            'Red Type Blend': ['gallon - Price: $185.00 (USD)', 'case - Price: $720.00 (USD)'],
            'Rice Crunchies Flavor': ['gallon - Price: $138.00 (USD)', 'case (4 gallons) - Price: $544.00 (USD)',
                                      'double case - Price: $1,080.00 (USD)'],
            'Ripe Banana Flavor **': ['gallon - Price: $99.75 (USD)', 'case - Price: $359.00 (USD)',
                                      'double case - Price: $670.00 (USD)'],
            'Root Beer Flavor (NF)': ['gallon - Price: $135.00 (USD)', 'case - Price: $528.00 (USD)',
                                      'double case - Price: $1,040.00 (USD)'],
            'Root Beer Flavor (PG) **': ['gallon - Price: $125.00 (USD)', 'case - Price: $488.00 (USD)',
                                         'double case - Price: $952.00 (USD)'],
            'Root Beer Flavor (Tri)': ['gallon - Price: $125.00 (USD)'],
            'Root Beer Float Flavor': ['gallon - Price: $129.00 (USD)', 'case - Price: $450.00 (USD)'],
            'Rose Candy Flavor': ['gallon - Price: $65.00 (USD)', 'case - Price: $302.00 (USD)'],
            'Ruby Chocolate Flavor': ['gallon - Price: $114.00 (USD)'],
            'RY4 Asian Flavor': ['gallon - Price: $132.00 (USD)', 'case - Price: $488.00 (USD)',
                                 'double case - Price: $944.00 (USD)'],
            'RY4 Double Flavor': ['gallon - Price: $119.00 (USD)', 'case - Price: $464.00 (USD)',
                                  'double case - Price: $904.00 (USD)'],
            'RY4 Double Flavor CC': ['gallon - Price: $119.00 (USD)'],
            'Ry4 Type Flavor**': ['gallon - Price: $135.00 (USD)', 'case - Price: $528.00 (USD)',
                                  'double case - Price: $1,040.00 (USD)'],
            'Saffron Flavor': ['gallon - Price: $148.00 (USD)'],
            'Sea Buckthorn Flavor': ['gallon - Price: $105.00 (USD)'],
            'Silly Rabbit Cereal Flavor': ['gallon - Price: $60.00 (USD)', 'case - Price: $320.00 (USD)'],
            'Slim Mint Cookie Flavor': ['gallon - Price: $275.00 (USD)'],
            'Smooth Flavor': ['gallon - Price: $105.00 (USD)', 'case - Price: $380.00 (USD)',
                              'double case - Price: $738.40 (USD)'],
            'Sour Flavor': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $332.00 (USD)',
                            'double case - Price: $648.00 (USD)'],
            'Spearmint Deluxe Flavor CC': ['gallon - Price: $119.70 (USD)'],
            'Spearmint Flavor': ['gallon - Price: $130.00 (USD)', 'case - Price: $500.00 (USD)',
                                 'double case - Price: $976.00 (USD)'],
            'Spearmint Menthol Flavor CC': ['gallon - Price: $119.70 (USD)'],
            'Spurberry Flavor**': ['gallon - Price: $145.70 (USD)', 'case (4 gallons) - Price: $576.00 (USD)',
                                   'double case - Price: $1,144.00 (USD)'],
            'Strawberries and Cream Flavor': ['gallon - Price: $96.90 (USD)', 'case (4 gallons) - Price: $376.00 (USD)',
                                              'double case - Price: $736.00 (USD)'],
            'Strawberry (Ripe) Flavor': ['gallon - Price: $119.70 (USD)', 'case (4 gallons) - Price: $468.00 (USD)',
                                         'double case - Price: $920.00 (USD)'],
            'Strawberry Flavor': ['gallon - Price: $105.00 (USD)', 'case (4) - Price: $408.00 (USD)',
                                  'double case - Price: $800.00 (USD)'],
            'Strawberry Lemonade Flavor': ['gallon - Price: $119.00 (USD)', 'case (4 gallons) - Price: $464.00 (USD)',
                                           'double case - Price: $904.00 (USD)'],
            'Strawberry Yogurt Flavor': ['gallon - Price: $140.90 (USD)', 'case (4 gallons) - Price: $556.00 (USD)',
                                         'double case - Price: $1,104.00 (USD)'],
            'Super Sweetener': ['gallon - Price: $115.00 (USD)', 'case (4 gallons) - Price: $440.00 (USD)',
                                'double case - Price: $840.00 (USD)'],
            'Swedish Gummy Flavor': ['gallon - Price: $120.00 (USD)', 'case (4 gallons) - Price: $472.00 (USD)',
                                     'double case - Price: $936.00 (USD)'],
            'Sweet and Tart Flavor': ['gallon - Price: $105.00 (USD)', 'case (4 gallons) - Price: $380.00 (USD)',
                                      'double case - Price: $698.40 (USD)'],
            'Sweet Cereal Flakes Flavor': ['gallon - Price: $75.00 (USD)', 'case (4 gallons) - Price: $435.00 (USD)',
                                           'double case - Price: $814.80 (USD)'],
            'Sweet Cream Flavor': ['gallon - Price: $102.60 (USD)', 'case (4 gallons) - Price: $400.00 (USD)',
                                   'double case - Price: $784.00 (USD)'],
            'Sweet Strawberry Flavor**': ['gallon - Price: $114.00 (USD)', 'case - Price: $416.00 (USD)',
                                          'double case - Price: $784.00 (USD)'],
            'Sweet Tea Flavor': ['gallon - Price: $143.10 (USD)', 'case - Price: $568.00 (USD)',
                                 'double case - Price: $1,120.00 (USD)'],
            'Sweet Tobacco Type Flavor CC': ['gallon - Price: $240.00 (USD)'],
            'Sweetener': ['gallon - Price: $85.50 (USD)', 'case (4 gallons) - Price: $336.00 (USD)',
                          'double case - Price: $656.00 (USD)'],
            'Taro Flavor': ['gallon - Price: $100.00 (USD)', 'case - Price: $360.00 (USD)',
                            'double case - Price: $680.00 (USD)'],
            'Tart and Sour Flavor': ['case (4 gallons) - Price: $484.00 (USD)', 'double case - Price: $960.00 (USD)'],
            'Tiramisu Flavor': ['gallon - Price: $180.00 (USD)'],
            'Toasted Almond Flavor': ['gallon - Price: $132.00 (USD)', 'case (4 gallons) - Price: $514.00 (USD)',
                                      'double case - Price: $960.00 (USD)'],
            'Toasted Marshmallow Flavor': ['gallon - Price: $129.00 (USD)', 'case (4 gallons) - Price: $508.00 (USD)',
                                           'double case - Price: $986.00 (USD)'],
            'Tobacco Flavor': ['gallon - Price: $102.60 (USD)', 'case - Price: $370.40 (USD)',
                               'double case - Price: $719.78 (USD)'],
            'Tobacco Type Flavor CC': ['gallon - Price: $148.00 (USD)'],
            'Turkish Flavor': ['gallon - Price: $129.00 (USD)', 'case - Price: $500.00 (USD)',
                               'double case - Price: $920.00 (USD)'],
            'Tutti Frutti Deluxe Flavor': ['gallon - Price: $114.00 (USD)', 'case - Price: $450.00 (USD)',
                                           'double case - Price: $880.00 (USD)'],
            'Tutti-Frutti Flavor **': ['gallon - Price: $85.50 (USD)', 'case - Price: $302.00 (USD)',
                                       'double case - Price: $584.00 (USD)'],
            'Madagascar Bourbon Vanilla Flavor': ['gallon - Price: $242.85 (USD)', 'case - Price: $952.00 (USD)'],
            'Vanilla Bean Gelato Flavor': ['gallon - Price: $168.00 (USD)', 'case (4 gallons) - Price: $664.00 (USD)',
                                           'double case - Price: $1,312.00 (USD)'],
            'Vanilla Bean Ice Cream Flavor': ['gallon - Price: $125.40 (USD)',
                                              'case (4 gallons) - Price: $461.60 (USD)',
                                              'double case - Price: $864.00 (USD)'],
            'Vanilla Cupcake': ['gallon - Price: $102.00 (USD)', 'case - Price: $380.00 (USD)',
                                'double case - Price: $675.12 (USD)'],
            'Vanilla Custard Flavor': ['gallon - Price: $130.00 (USD)', 'case - Price: $504.00 (USD)',
                                       'double case - Price: $984.00 (USD)'],
            'Vanilla Custard II Flavor': ['gallon - Price: $142.50 (USD)', 'case - Price: $554.00 (USD)'],
            'Vanilla Swirl Flavor': ['gallon - Price: $120.00 (USD)', 'case (4 gallons) - Price: $440.00 (USD)',
                                     'double case - Price: $820.00 (USD)'],
            'Vanillin 10 (PG)': ['gallon - Price: $84.00 (USD)', 'case (4 gallons) - Price: $328.00 (USD)',
                                 'double case - Price: $640.00 (USD)'],
            'Waffle (Belgian) Flavor': ['gallon - Price: $129.00 (USD)', 'case - Price: $476.00 (USD)',
                                        'double case - Price: $920.00 (USD)'],
            'Waffle Flavor **': ['gallon - Price: $91.20 (USD)', 'case - Price: $356.00 (USD)'],
            'Watermelon (VG) Flavor': ['gallon - 2 week lead time - Price: $85.50 (USD)',
                                       'case - Price: $302.00 (USD)'],
            'Watermelon Candy Flavor': ['gallon - Price: $120.00 (USD)', 'case (4 gallons) - Price: $440.00 (USD)',
                                        'double case - Price: $807.04 (USD)'],
            'Watermelon Flavor': ['gallon - Price: $142.50 (USD)', 'case (4 gallons) - Price: $556.00 (USD)',
                                  'double case - Price: $1,096.00 (USD)'],
            'Western Flavor': ['gallon - Price: $148.20 (USD)', 'case - Price: $520.00 (USD)',
                               'double case - Price: $931.20 (USD)'],
            'Western Flavor CC': ['gallon - Price: $148.20 (USD)'],
            'Western II Flavor': ['gallon - Price: $148.20 (USD)', 'case - Price: $520.00 (USD)',
                                  'double case - Price: $931.20 (USD)'],
            'Whipped Cream Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $316.50 (USD)',
                                     'double case - Price: $547.08 (USD)'],
            'White Chocolate Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $300.00 (USD)',
                                       'double case - Price: $524.00 (USD)'],
            'Wintergreen Deluxe Flavor CC': ['gallon - Price: $125.00 (USD)'],
            'Wintergreen Flavor': ['gallon - Price: $85.50 (USD)', 'case - Price: $300.00 (USD)'],
            'WS-23 30%': ['gallon - Price: $240.00 (USD)', 'case - Price: $928.00 (USD)',
                          'double case - Price: $1,848.00 (USD)'], 'Yam Flavor': ['gallon - Price: $50.00 (USD)'],
            'Zesty Tobacco Type Flavor CC': ['gallon - Price: $240.00 (USD)']}

    def login(self):
        self.open_tpa()
        self.page.fill(self.EMAIL_FIELD, Credentials.APP_USERNAME)
        self.page.fill(self.PASSWORD_FIELD, Credentials.APP_PASSWORD)
        self.page.click(self.LOGIN_BUTTON)

    def get_aromas(self):
        self.page.goto('https://shop.perfumersapprentice.com/c-84-bulk-sizes.aspx')
        aroma_blocks = self.page.locator(self.AROMA_BLOCK).all()
        for block in aroma_blocks:
            aroma_name = block.locator("h2").text_content()
            price_blocks = block.locator('.addtocart select option').all()
            prices = []
            for price_block in price_blocks:
                aroma_price = price_block.text_content()
                prefix = aroma_price[0:4]
                if 'gall' in prefix:
                    prices.append(aroma_price.replace(str('\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t'), 'Price: '))
                elif prefix == 'case':
                    prices.append(aroma_price.replace(str('\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t'), 'Price: ')
                                  .replace(' (4) 2week lead time', ''))
                elif prefix == 'doub':
                    prices.append(aroma_price.replace(str('\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t'), 'Price: ').
                                  replace(' (8) 2 week lead time', ''))
            if prices:
                self.names_list.update({aroma_name: prices})

    def compare_dicts(self):
        send_telegram('www.youtube.com/watch?v=fUdsmUbs3s0')
        names_list = self.names_list
        data = self.data
        added, removed, modified, same = dict_compare(names_list, data)
        for products, prises_list in modified.items():
            arr = prises_list[0]
            arr2 = prises_list[1]
            i = 0
            if len(arr) == len(arr2):
                while i < len(arr):
                    if arr[i] != arr2[i]:
                        time.sleep(10)
                        print(f"\n{products}\nold:{arr2[i]} \nnew:{arr[i]}")
                        # send_telegram(f"\n{products}\nold:{arr2[i]} \nnew:{arr[i]}")

                        i += 1
                    else:
                        i += 1
            else:
                time.sleep(10)
                print(f'\nNew position was added/removed:\nOld file:{products}{arr2} '
                      f'\nNew file:{products}{arr}')
                # send_telegram(f'\nNew position was added/removed:\nOld file:{products}{arr2} '
                #       f'\nNew file:{products}{arr}')

